### ISSUE TITLE
Cron problem

### ISSUE THREAD

**Issue by aplalmeida** [pozgo/docker-cacti#10]
After deploying with "docker-compose up" the cron schedule poller is not working.
I don´t know if I did some thing wrong, I´m looking for solution.
If I run manually works fine.

**Comment by pozgo** [comment]
Hi,

Please be more specific. ;) Attach your `docker-compose.yaml` for investigation. 
I would say that you have done something wrong if the image is working ok when run manually.

**Comment by aplalmeida** [comment]
Hi,

Sorry.

I just rename from docker-cloud.yml to docker-compose.yml and changed ports.

#########################################
cacti-db:
  image: million12/mariadb
  environment:
    MARIADB_USER: cactiuser
    MARIADB_PASS: my_password

cacti:
  image: polinux/cacti
  links:
    - cacti-db
  ports:
    - "8081:80"
    - "4443:443"
  environment:
    DB_USER: cactiuser
    DB_PASS: my_password
    DB_ADDRESS: cacti-db

**Comment by pozgo** [comment]
Try redownloading latest image. And see if that helps.

**Comment by pozgo** [comment]
All seems to work ok. Closing
